version: "3.9"
services:
  honeybot:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: honeybot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../storage:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
